require "./lib/passenger"
require "./lib/vehicle"
require "./lib/park"

RSpec.describe Park do
  describe "#initialize" do
    it "exists" do
      park = Park.new("Windmill Park", 5)
      
      expect(park).to be_a(Park)
    end
  end
  
  describe "#name" do
    it "returns name of the park" do
      park = Park.new("Windmill Park", 5)
      
      expect(park.name).to eq("Windmill Park")
    end
  end
  
  describe "#admission_price" do
    it "returns admission price of the park" do
      park = Park.new("Windmill Park", 5)
      
      expect(park.admission_price).to eq(5)
    end
  end
  
  describe "#vehicles" do
    it "returns vehicles that have entered the park" do
      park = Park.new("Windmill Park", 5)
      
      expect(park.vehicles).to eq([])
    end
  end
  
  describe "#add_vehicle" do
    it "adds vehicle to the park" do
      park = Park.new("Windmill Park", 5)
      vehicle = Vehicle.new("2001", "Honda", "Civic")

      park.add_vehicle(vehicle)

      expect(park.vehicles).to eq([vehicle])
    end
  end

  describe "#passengers" do
    it "returns passengers of vehicles that entered the park" do
      park = Park.new("Windmill Park", 5)
      vehicle = Vehicle.new("2001", "Honda", "Civic")
      charlie = Passenger.new({"name" => "Charlie", "age" => 18})
      jude = Passenger.new({"name" => "Jude", "age" => 20})    
      taylor = Passenger.new({"name" => "Taylor", "age" => 12})

      vehicle.add_passenger(charlie)
      vehicle.add_passenger(jude)
      vehicle.add_passenger(taylor)

      park.add_vehicle(vehicle)

      expect(park.passengers).to eq([charlie, jude, taylor])
    end
  end

  describe "#revenue" do
    it "returns revenue generated by parks visitors" do
      park = Park.new("Windmill Park", 5)
      vehicle = Vehicle.new("2001", "Honda", "Civic")
      charlie = Passenger.new({"name" => "Charlie", "age" => 18})
      jude = Passenger.new({"name" => "Jude", "age" => 20})    
      taylor = Passenger.new({"name" => "Taylor", "age" => 12})

      vehicle.add_passenger(charlie)
      vehicle.add_passenger(jude)
      vehicle.add_passenger(taylor)

      park.add_vehicle(vehicle)

      expect(park.revenue).to eq(10)
    end
  end

  describe "#all_attendees" do
    it "returns all attendees names, sorted alphabetically" do
      park = Park.new("Windmill Park", 5)
      vehicle = Vehicle.new("2001", "Honda", "Civic")
      charlie = Passenger.new({"name" => "Charlie", "age" => 18})
      jude = Passenger.new({"name" => "Jude", "age" => 20})    
      taylor = Passenger.new({"name" => "Taylor", "age" => 12})
      jill = Passenger.new({"name" => "Jill", "age" => 10})

      vehicle.add_passenger(charlie)
      vehicle.add_passenger(jude)
      vehicle.add_passenger(taylor)
      vehicle.add_passenger(jill)

      park.add_vehicle(vehicle)

      expect(park.all_attendees(park)).to eq(["Charlie", "Jill", "Jude", "Taylor"])
    end
  end

  xdescribe "#minors" do
    it "returns all minors names, sorted alphabetically" do
      park = Park.new("Windmill Park", 5)
      vehicle = Vehicle.new("2001", "Honda", "Civic")
      charlie = Passenger.new({"name" => "Charlie", "age" => 18})
      jude = Passenger.new({"name" => "Jude", "age" => 20})    
      taylor = Passenger.new({"name" => "Taylor", "age" => 12})
      jill = Passenger.new({"name" => "Jill", "age" => 10})

      vehicle.add_passenger(charlie)
      vehicle.add_passenger(jude)
      vehicle.add_passenger(taylor)
      vehicle.add_passenger(jill)

      park.add_vehicle(vehicle)

      expect(park.minors(park)).to eq(["Jill", "Taylor"])
    end
  end

  xdescribe "#adults" do
    it "returns all adults names, sorted alphabetically" do
      park = Park.new("Windmill Park", 5)
      vehicle = Vehicle.new("2001", "Honda", "Civic")
      charlie = Passenger.new({"name" => "Charlie", "age" => 18})
      jude = Passenger.new({"name" => "Jude", "age" => 20})    
      taylor = Passenger.new({"name" => "Taylor", "age" => 12})
      jill = Passenger.new({"name" => "Jill", "age" => 10})
      eliza = Passenger.new({"name" => "Eliza", "age" => 21})

      vehicle.add_passenger(charlie)
      vehicle.add_passenger(jude)
      vehicle.add_passenger(taylor)
      vehicle.add_passenger(jill)
      vehicle.add_passenger(eliza)

      park.add_vehicle(vehicle)

      expect(park.adults).to eq(["Charlie", "Eliza", "Jude"])
    end
  end
end